### ISSUE TITLE
Build fails with 2.067.0

### ISSUE THREAD

**Issue by LightBender** [andersonpd/eris#3]
The following errors are reported when attempting to include eris via dub.

...\dub\packages\eris-0.0.1\eris\integer\extended.d(597): Error: redundant attribute 'const'
...\dub\packages\eris-0.0.1\eris\integer\extended.d(597): Error: redundant attribute 'const'
...\dub\packages\eris-0.0.1\eris\integer\extended.d(597): Error: redundant attribute 'const'
...\dub\packages\eris-0.0.1\eris\integer\extended.d(632): Error: redundant attribute 'const'

**Comment by andersonpd** [comment]
My bad.

I thought it was remarkable when I accidentally added 'const' to an already 'const' function and it still compiled. It was so remarkable that I deliberately added an extra 'const' in a couple of places to be sure. BUT-- I forgot to delete the extra consts after my little test, and now that bug has apparently been fixed. Hence the error.

I'm right in the middle of some other changes and I'll push them tomorrow (it's almost midnight here) along with the fix for extended.d.

Paul

**Comment by andersonpd** [comment]
I pushed the changes to fix the redundant 'const' modifiers. Should be good to go now.

**Comment by andersonpd** [comment]
Re-opened. Didn't mean to close it the first time.
